### PR TITLE
lavender: update to V11.0.7.0

### PR DESCRIPTION
**Pull request by erikcas**
https://github.com/xiaomi-sdm660/android_device_xiaomi_lavender/pull/3

### CODE REVIEW

**Comment by erikcas** [comment]
**REQUIRES** https://github.com/choose-a/android_kernel_xiaomi_lavender/commit/03515f4b8522f6fbb7142a95dadc80c1af4e66e9

taken from

https://github.com/AmulyaX/android_kernel_xiaomi_sdm660/commit/3e3cd82b0cde9d9e08b8be6c1ffc035cf456c707#diff-cd0c826d29a8da963e9c7a48f732ff4c

**Comment by erikcas** [comment]
Just in case, I am having surgery coming up, and anyone would like to implement 10 blobs, take this as a starting point:

https://github.com/choose-a/android_vendor_xiaomi_lavender/tree/choose-10-10
for propr filelist, delete

- vendor/lib/hw/gatekeeper.sdm660.so
- vendor/lib64/hw/gatekeeper.sdm660.so

and add

- vendor/firmware/cpp_firmware_v1_12_1.fw
- vendor/lib/libdng_sdkvendor.so

from/to the V11.0.7.0 proprietary-files.txt

also update your firmware to 20.3.6!

https://dl.choose-a.name/choose-a/lavender/ten/firmwares/

this boots, but camera not working

**Comment by Manish4586** [comment]
If this update breaks the camera then investigate the issue and fix it then push again.

**Comment by rcstar6696** [comment]
Its ok i talked with him he should open it as he has to keave android for some time and want to share his current status with us

**Comment by Manish4586** [comment]
@rcstar6696 ok bro
@erikcas get well soon bro

**Comment by rena2806** [comment]
> If this update breaks the camera then investigate the issue and fix it then push again.

This update does not break the camera - it provided the necessary commit for updating in the kernel

**Comment by Manish4586** [comment]
@rena2806

**Comment by rena2806** [comment]
> @rena2806

Wassap?

**Comment by erikcas** [comment]
This pr + kernel chance breaks no camera. The third post describes a little startup tot import 10 blond for lavender. So this pr will not affect camera if the described kernel commit is user.

Sorry for inconvenience.

**Comment by erikcas** [comment]
@renascape  as I understand, you had some issues with this pr? Correct? If yes, what are the issues? I am somewhat recovered, and want to solve existing issues in this pr.

**Pull request closed without merging**
